# Generated by Django 3.2 on 2021-04-18 19:35

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('position', models.CharField(choices=[('S', 'Supervisor'), ('I', 'Instructor'), ('T', 'Ta')], default='T', max_length=1)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TAsToCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.coursedata')),
            ],
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('TA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalApp.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.coursedata')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.coursedata')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalApp.myuser')),
            ],
        ),
    ]
