# Generated by Django 3.2 on 2021-04-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('S', 'Supervisor'), ('I', 'Instructor'), ('T', 'Ta')], default='T', max_length=1),
        ),
    ]
