# Generated by Django 3.2 on 2021-05-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_auto_20210426_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='address',
            new_name='addressln1',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='designation',
            field=models.CharField(default='cs351', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='addressln2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coursesections',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tastocourses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TASkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.myuser')),
            ],
        ),
    ]
