# Generated by Django 3.2 on 2021-04-17 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_myuser_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='TAsToCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.coursedata')),
            ],
        ),
        migrations.CreateModel(
            name='LabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalApp.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.coursedata')),
            ],
        ),
        migrations.AddField(
            model_name='coursedata',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalApp.myuser'),
        ),
    ]
