# Generated by Django 3.2 on 2021-05-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0005_auto_20210510_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskills',
            name='TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.myuser', unique=True),
        ),
    ]
