# Generated by Django 3.2 on 2021-05-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0006_alter_taskills_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskills',
            name='TA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalApp.myuser'),
        ),
    ]
