# Generated by Django 3.2 on 2021-05-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0006_auto_20210513_1708'),
        ('finalApp', '0007_alter_taskills_ta'),
    ]

    operations = [
    ]
