# Generated by Django 3.2 on 2021-05-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0009_auto_20210515_2237'),
        ('finalApp', '0009_auto_20210517_1955'),
    ]

    operations = [
    ]
